[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tokenico = "6utJEwmhwa51QVfi6PpH6AEgk27cfLBS3TGfGAVe9oCf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mathan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
